spring:
  datasource:
    url: jdbc:h2:file:./data/restaurant;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
server:
  port: 8080
  servlet:
    context-path: /api
logging:
  level:
    com.restaurant: INFO
    org.springframework: WARN
